version 15
SingTel-DataCo/DS_genome_api pull request #19
Opened 2021-05-05 05:13 UTC by ypan6199

+ fix bound bug
+ DataRoom class

2021-05-25 06:15 UTC, ypan6199 commented
@richardellison @Jingxuan-Wang  

+ abs_sa_hierarchy.csv to dataroom
+ fix bug in total_records of staypoint
+ Dataroom class
+ fix bound bug
+ new package

2021-05-31 02:40 UTC, Jingxuan-Wang requested changes

2021-05-31 02:40 UTC, Jingxuan-Wang commented on genomeapi/api/dataroom.py
> +        "lm": "Discrete Visit"
is this an error?

2021-05-31 03:11 UTC, Jingxuan-Wang approved these changes

2021-05-31 03:12 UTC, merged